
name: PR Logger

on:
  pull_request:
  workflow_dispatch:

jobs:
  log_pr_changes:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: dependencies
        run: |
          pip install boto3

      - name: get brach and main
        run: |
          git fetch origin ${{ github.base_ref }}
          git fetch origin ${{ github.head_ref }}

      - name: diff files
        id: files
        run: echo "::set-output name=files::$(git diff-tree --name-only -r --merge-base origin/${{ github.event.pull_request.base.ref }} origin/${{ github.head_ref }})"


      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::654654242440:role/github-oidc-role
          aws-region: ${{ env.AWS_REGION }}

      - name: log changes pull request upload to aws
        env:
          CHANGED_FILES: ${{ steps.files.outputs.files }}
          REPO_NAME: ${{ github.repository }}
        run: python log_changes.py
